title: Will Luna # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/willluna/">LinkedIn</a> 
  <br><br>
  <a href="https://www.kaggle.com/wluna01">Kaggle</a> 
  <br><br>
  <a href="https://twitter.com/wluna01">Twitter</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
