title: Will Luna # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/willluna/" target="_blank">LinkedIn</a> 
  <br>
  <a href="https://www.kaggle.com/wluna01/notebooks" target="_blank">Kaggle</a>
  <br>
  <a href="https://twitter.com/wluna01" target="_blank">Twitter</a> 
  <br>
  <br>
  <h2>Writing</h2>
  <a href="https://lunaandchris.wordpress.com/2016/12/04/in-a-perfect-world/" target="_blank">Reflections on my first mobile app</a>
  <br>
  <a href="https://medium.com/@784485/miyazakis-sonic-mark-b0cd1c83b465" target="_blank">Joe Hisaishi's film scoring</a>
  <br>
  <a href="https://docs.google.com/document/d/1vknwB6BdSsOUQuaSAa46jLrRonGvW07DUEMmM-WDg-s/edit?usp=sharing" target="_blank">Dynamic video game music</a>
theme: jekyll-theme-minimal
google_analytics: UA-152639068-1 # your Google Analytics tracking ID here
