title: Will Luna # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><strong>Work</strong>  
    <br>Data Engineer, Meta
    <br>Analytics Engineer, Anaconda
    <br>Data Analyst, Sanity
  <br><strong>Education</strong>
    <br>MS Computer Science, Georgia Tech
    <br>BA Cognitive Science, Tufts University
  <br><a href="https://www.linkedin.com/in/willluna/" target="_blank">LinkedIn</a>
theme: jekyll-theme-minimal
google_analytics: UA-152639068-1 # your Google Analytics tracking ID here
